<a href="https://colab.research.google.com/github/MateoGlz/AdmiTareas-BackEnd/blob/main/_4_Manipulaci%C3%B3n_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

griffith = np.random.randint(1, 11, size=(3, 3))
guts = np.random.randint(1, 11, size=(3, 3))

print("Griffith:")
print(griffith)

print("\nGuts:")
print(guts)

sum_matrix = griffith + guts
print("\nSuma de matrices:")
print(sum_matrix)

subtract_matrix = griffith - guts
print("\nResta de matrices (Griffith - Guts):")
print(subtract_matrix)

multiply_scalar_matrix = griffith * 2
print("\nMultiplicación de Griffith por 2:")
print(multiply_scalar_matrix)

matrix_product = np.dot(griffith, guts)
print("\nMultiplicación matricial (Griffith  * Guts):")
print(matrix_product)

Griffith:
[[10  9  5]
 [ 6  4  3]
 [ 5  1  8]]

Guts:
[[8 8 4]
 [2 6 4]
 [9 9 3]]

Suma de matrices:
[[18 17  9]
 [ 8 10  7]
 [14 10 11]]

Resta de matrices (Griffith - Guts):
[[ 2  1  1]
 [ 4 -2 -1]
 [-4 -8  5]]

Multiplicación de Griffith por 2:
[[20 18 10]
 [12  8  6]
 [10  2 16]]

Multiplicación matricial (Griffith  * Guts):
[[143 179  91]
 [ 83  99  49]
 [114 118  48]]
